package Usuario;

import static Catalogo.formCatalogo.cadastrar;
import javax.swing.JOptionPane;
import javax.management.StringValueExp;
import javax.swing.JFrame;

public class formLogin extends javax.swing.JFrame {
    /**
     * Creates new form JframeUsuarioLogin
     */
    public formLogin() {
        initComponents();
        setLocationRelativeTo(null);
        //setExtendedState(MAXIMIZED_BOTH);
    }
    
            

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblTitulo2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        pswSenha = new javax.swing.JPasswordField();
        txtCliente = new javax.swing.JTextField();
        btnConfirmarLogin = new javax.swing.JButton();
        lblCadastro = new javax.swing.JLabel();
        btn_login_voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(3, 54, 73));

        lblTitulo.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(232, 221, 203));
        lblTitulo.setText("Faça Login na");
        lblTitulo.setName("lblLogin"); // NOI18N

        lblTitulo2.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        lblTitulo2.setForeground(new java.awt.Color(232, 221, 203));
        lblTitulo2.setText("na sua conta");
        lblTitulo2.setName("lblLogin"); // NOI18N

        jPanel2.setBackground(new java.awt.Color(232, 221, 203));

        lblUsuario.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(3, 54, 73));
        lblUsuario.setLabelFor(txtCliente);
        lblUsuario.setText("E-mail ou CPF:");
        lblUsuario.setName("lblUsuarioLogin"); // NOI18N

        lblSenha.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblSenha.setForeground(new java.awt.Color(3, 54, 73));
        lblSenha.setLabelFor(pswSenha);
        lblSenha.setText("Senha:");
        lblSenha.setName("lblSenhaLogin"); // NOI18N

        pswSenha.setBackground(new java.awt.Color(232, 221, 203));
        pswSenha.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        pswSenha.setForeground(new java.awt.Color(3, 54, 73));
        pswSenha.setName("txtSenhaLogin"); // NOI18N
        pswSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pswSenhaActionPerformed(evt);
            }
        });

        txtCliente.setBackground(new java.awt.Color(232, 221, 203));
        txtCliente.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        txtCliente.setForeground(new java.awt.Color(3, 54, 73));
        txtCliente.setName("txtUsuarioLogin"); // NOI18N
        txtCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteActionPerformed(evt);
            }
        });

        btnConfirmarLogin.setBackground(new java.awt.Color(205, 179, 128));
        btnConfirmarLogin.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnConfirmarLogin.setForeground(new java.awt.Color(3, 54, 73));
        btnConfirmarLogin.setText("Confirmar");
        btnConfirmarLogin.setFocusable(false);
        btnConfirmarLogin.setName("btnConfirmarLogin"); // NOI18N
        btnConfirmarLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarLoginActionPerformed(evt);
            }
        });

        lblCadastro.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        lblCadastro.setForeground(new java.awt.Color(3, 54, 73));
        lblCadastro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCadastro.setText("Cadastre-se");
        lblCadastro.setName("LblCadastro"); // NOI18N
        lblCadastro.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblCadastroMouseMoved(evt);
            }
        });
        lblCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCadastroMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCadastroMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblCadastro)
                        .addGap(27, 27, 27)
                        .addComponent(btnConfirmarLogin))
                    .addComponent(lblSenha, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsuario, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(pswSenha, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(23, 23, 23))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(lblUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lblSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pswSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmarLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCadastro))
                .addGap(23, 23, 23))
        );

        btn_login_voltar.setBackground(new java.awt.Color(205, 179, 128));
        btn_login_voltar.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btn_login_voltar.setForeground(new java.awt.Color(3, 54, 73));
        btn_login_voltar.setText("Voltar");
        btn_login_voltar.setFocusable(false);
        btn_login_voltar.setName("btn_login_voltar"); // NOI18N
        btn_login_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_login_voltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_login_voltar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTitulo2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(62, 62, 62)
                    .addComponent(lblTitulo)
                    .addContainerGap(550, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(lblTitulo2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(129, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)))
                .addComponent(btn_login_voltar)
                .addGap(42, 42, 42))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(130, 130, 130)
                    .addComponent(lblTitulo)
                    .addContainerGap(353, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteActionPerformed
        
    }//GEN-LAST:event_txtClienteActionPerformed

    private void pswSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pswSenhaActionPerformed
        
    }//GEN-LAST:event_pswSenhaActionPerformed


    private void btnConfirmarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarLoginActionPerformed
        String textf = txtCliente.getText();
        String senhaf = new String(pswSenha.getPassword());
        
        Cliente.consultarClientes(textf, senhaf);
        
        dispose();
    }//GEN-LAST:event_btnConfirmarLoginActionPerformed

    private void btn_login_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_login_voltarActionPerformed
        txtCliente.setText("");
        pswSenha.setText("");
        dispose();
    }//GEN-LAST:event_btn_login_voltarActionPerformed

    private void lblCadastroMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadastroMouseMoved
        int x = 0;
        int y = 51;
        int z = 255;
        
        lblCadastro.setForeground(new java.awt.Color(x, y, z));
    }//GEN-LAST:event_lblCadastroMouseMoved

    private void lblCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadastroMouseClicked
        formCadastrar cadastro = new formCadastrar();
        cadastro.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblCadastroMouseClicked

    private void lblCadastroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadastroMouseExited
        int x = 3;
        int y = 54;
        int z = 73;
        
        lblCadastro.setForeground(new java.awt.Color(x, y, z));
    }//GEN-LAST:event_lblCadastroMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        new formLogin();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmarLogin;
    private javax.swing.JButton btn_login_voltar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCadastro;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTitulo2;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPasswordField pswSenha;
    private javax.swing.JTextField txtCliente;
    // End of variables declaration//GEN-END:variables
}
