package Usuario;

import javax.swing.JOptionPane;
import javax.swing.JFrame;
import java.util.Scanner;
import java.io.IOException;



public class formCadastrar extends javax.swing.JFrame {
    

    /**
     * Creates new form JframeUsuarioCadastrar
     */
    
    public formCadastrar() {
        initComponents();
        setLocationRelativeTo(null);
        //setExtendedState(MAXIMIZED_BOTH);
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblSubtitulo = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        btnConfirmar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        lblPossuoCadastro = new javax.swing.JLabel();
        lblTitulo2 = new javax.swing.JLabel();
        lblTitulo3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblNome = new javax.swing.JLabel();
        lblRequisitos1 = new javax.swing.JLabel();
        pswSenha = new javax.swing.JPasswordField();
        txtNome = new javax.swing.JTextField();
        lblCPF = new javax.swing.JLabel();
        txtCPF = new javax.swing.JTextField();
        lblConfirmarSenha = new javax.swing.JLabel();
        pswConfirmarSenha = new javax.swing.JPasswordField();
        lblRequisitos2 = new javax.swing.JLabel();
        lblRequisitos3 = new javax.swing.JLabel();
        txtCEP = new javax.swing.JTextField();
        lblCPF1 = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        lblBairro = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        lblCidade = new javax.swing.JLabel();
        txtLogradouro = new javax.swing.JTextField();
        lblCidade1 = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        cmbEstado = new javax.swing.JComboBox<>();
        txtNumero = new javax.swing.JTextField();
        lblNumero = new javax.swing.JLabel();
        cbxNumero = new javax.swing.JCheckBox();
        txtComplemento = new javax.swing.JTextField();
        lblComplemento = new javax.swing.JLabel();
        lblObrigatorio1 = new javax.swing.JLabel();
        lblObrigatorio2 = new javax.swing.JLabel();
        lblObrigatorio3 = new javax.swing.JLabel();
        lblObrigatorio = new javax.swing.JLabel();
        lblObrigatorio4 = new javax.swing.JLabel();
        lblObrigatorio5 = new javax.swing.JLabel();
        lblObrigatorio6 = new javax.swing.JLabel();
        lblObrigatorio7 = new javax.swing.JLabel();
        lblObrigatorio8 = new javax.swing.JLabel();
        lblObrigatorio9 = new javax.swing.JLabel();
        lblObrigatorio10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(3, 54, 73));
        jPanel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        lblTitulo.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(232, 221, 203));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Cadastro");
        lblTitulo.setName("lblCadastro"); // NOI18N

        lblSubtitulo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblSubtitulo.setForeground(new java.awt.Color(232, 221, 203));
        lblSubtitulo.setLabelFor(txtEmail);
        lblSubtitulo.setText("Por favor insira seu dados corretamente em todos campos obrigatórios abaixo.");
        lblSubtitulo.setName("lblUsuarioCadastro"); // NOI18N

        txtEmail.setBackground(new java.awt.Color(232, 221, 203));
        txtEmail.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(0, 0, 0));
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        lblEmail.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(232, 221, 203));
        lblEmail.setLabelFor(txtEmail);
        lblEmail.setText("Email:");
        lblEmail.setName("lblUsuarioCadastro"); // NOI18N

        lblSenha.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblSenha.setForeground(new java.awt.Color(232, 221, 203));
        lblSenha.setLabelFor(pswSenha);
        lblSenha.setText("Senha:");
        lblSenha.setName("lblSenhaCadastro"); // NOI18N

        btnConfirmar.setBackground(new java.awt.Color(205, 179, 128));
        btnConfirmar.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnConfirmar.setForeground(new java.awt.Color(3, 54, 73));
        btnConfirmar.setText("Cadastrar");
        btnConfirmar.setFocusable(false);
        btnConfirmar.setName("btnConfirmar"); // NOI18N
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        btnVoltar.setBackground(new java.awt.Color(205, 179, 128));
        btnVoltar.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(3, 54, 73));
        btnVoltar.setText("Voltar");
        btnVoltar.setFocusable(false);
        btnVoltar.setName("btnVoltar"); // NOI18N
        btnVoltar.setPreferredSize(new java.awt.Dimension(86, 23));
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        lblPossuoCadastro.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        lblPossuoCadastro.setForeground(new java.awt.Color(232, 221, 203));
        lblPossuoCadastro.setText("Já possuo conta");
        lblPossuoCadastro.setName("lblPossuoCadastro"); // NOI18N
        lblPossuoCadastro.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblPossuoCadastroMouseMoved(evt);
            }
        });
        lblPossuoCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPossuoCadastroMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblPossuoCadastroMouseExited(evt);
            }
        });

        lblTitulo2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblTitulo2.setForeground(new java.awt.Color(232, 221, 203));
        lblTitulo2.setLabelFor(txtEmail);
        lblTitulo2.setText("Dados");
        lblTitulo2.setName("lblUsuarioCadastro"); // NOI18N

        lblTitulo3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblTitulo3.setForeground(new java.awt.Color(232, 221, 203));
        lblTitulo3.setLabelFor(txtEmail);
        lblTitulo3.setText("Endereço");
        lblTitulo3.setName("lblUsuarioCadastro"); // NOI18N

        jSeparator1.setForeground(new java.awt.Color(232, 221, 203));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lblNome.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblNome.setForeground(new java.awt.Color(232, 221, 203));
        lblNome.setLabelFor(txtEmail);
        lblNome.setText("Nome:");
        lblNome.setName("lblUsuarioCadastro"); // NOI18N

        lblRequisitos1.setFont(new java.awt.Font("Arial", 2, 10)); // NOI18N
        lblRequisitos1.setForeground(new java.awt.Color(232, 221, 203));
        lblRequisitos1.setLabelFor(pswSenha);
        lblRequisitos1.setText("Pelo menos 8 carácteres,");
        lblRequisitos1.setName("lblSenhaCadastro"); // NOI18N

        pswSenha.setBackground(new java.awt.Color(232, 221, 203));
        pswSenha.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        pswSenha.setForeground(new java.awt.Color(0, 0, 0));
        pswSenha.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pswSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pswSenhaActionPerformed(evt);
            }
        });

        txtNome.setBackground(new java.awt.Color(232, 221, 203));
        txtNome.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtNome.setForeground(new java.awt.Color(0, 0, 0));
        txtNome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        lblCPF.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblCPF.setForeground(new java.awt.Color(232, 221, 203));
        lblCPF.setLabelFor(txtEmail);
        lblCPF.setText("CPF:");
        lblCPF.setName("lblUsuarioCadastro"); // NOI18N

        txtCPF.setBackground(new java.awt.Color(232, 221, 203));
        txtCPF.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txtCPF.setForeground(new java.awt.Color(0, 0, 0));

        lblConfirmarSenha.setFont(new java.awt.Font("Arial", 1, 19)); // NOI18N
        lblConfirmarSenha.setForeground(new java.awt.Color(232, 221, 203));
        lblConfirmarSenha.setLabelFor(pswSenha);
        lblConfirmarSenha.setText("Confirmar Senha:");
        lblConfirmarSenha.setName("lblSenhaCadastro"); // NOI18N

        pswConfirmarSenha.setBackground(new java.awt.Color(232, 221, 203));
        pswConfirmarSenha.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        pswConfirmarSenha.setForeground(new java.awt.Color(0, 0, 0));
        pswConfirmarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pswConfirmarSenhaActionPerformed(evt);
            }
        });

        lblRequisitos2.setFont(new java.awt.Font("Arial", 2, 10)); // NOI18N
        lblRequisitos2.setForeground(new java.awt.Color(232, 221, 203));
        lblRequisitos2.setLabelFor(pswSenha);
        lblRequisitos2.setText("1 letra maiúscula e 1 minúscula,");
        lblRequisitos2.setName("lblSenhaCadastro"); // NOI18N

        lblRequisitos3.setFont(new java.awt.Font("Arial", 2, 10)); // NOI18N
        lblRequisitos3.setForeground(new java.awt.Color(232, 221, 203));
        lblRequisitos3.setLabelFor(pswSenha);
        lblRequisitos3.setText("1 número e um símbolo (!@#$%&).");
        lblRequisitos3.setName("lblSenhaCadastro"); // NOI18N

        txtCEP.setBackground(new java.awt.Color(232, 221, 203));
        txtCEP.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txtCEP.setForeground(new java.awt.Color(0, 0, 0));
        txtCEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCEPActionPerformed(evt);
            }
        });

        lblCPF1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblCPF1.setForeground(new java.awt.Color(232, 221, 203));
        lblCPF1.setLabelFor(txtEmail);
        lblCPF1.setText("CEP:");
        lblCPF1.setName("lblUsuarioCadastro"); // NOI18N

        txtBairro.setBackground(new java.awt.Color(232, 221, 203));
        txtBairro.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtBairro.setForeground(new java.awt.Color(0, 0, 0));
        txtBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBairroActionPerformed(evt);
            }
        });

        lblBairro.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblBairro.setForeground(new java.awt.Color(232, 221, 203));
        lblBairro.setLabelFor(txtEmail);
        lblBairro.setText("Bairro:");
        lblBairro.setName("lblUsuarioCadastro"); // NOI18N

        txtCidade.setBackground(new java.awt.Color(232, 221, 203));
        txtCidade.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtCidade.setForeground(new java.awt.Color(0, 0, 0));
        txtCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCidadeActionPerformed(evt);
            }
        });

        lblCidade.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblCidade.setForeground(new java.awt.Color(232, 221, 203));
        lblCidade.setLabelFor(txtEmail);
        lblCidade.setText("Cidade:");
        lblCidade.setName("lblUsuarioCadastro"); // NOI18N

        txtLogradouro.setBackground(new java.awt.Color(232, 221, 203));
        txtLogradouro.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtLogradouro.setForeground(new java.awt.Color(0, 0, 0));
        txtLogradouro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLogradouroActionPerformed(evt);
            }
        });

        lblCidade1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblCidade1.setForeground(new java.awt.Color(232, 221, 203));
        lblCidade1.setLabelFor(txtEmail);
        lblCidade1.setText("Logradouro:");
        lblCidade1.setName("lblUsuarioCadastro"); // NOI18N

        lblEstado.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblEstado.setForeground(new java.awt.Color(232, 221, 203));
        lblEstado.setLabelFor(txtEmail);
        lblEstado.setText("Estado:");
        lblEstado.setName("lblUsuarioCadastro"); // NOI18N

        cmbEstado.setBackground(new java.awt.Color(232, 221, 203));
        cmbEstado.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha uma opção", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        txtNumero.setBackground(new java.awt.Color(232, 221, 203));
        txtNumero.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtNumero.setForeground(new java.awt.Color(0, 0, 0));
        txtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroActionPerformed(evt);
            }
        });

        lblNumero.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblNumero.setForeground(new java.awt.Color(232, 221, 203));
        lblNumero.setLabelFor(txtEmail);
        lblNumero.setText("Número:");
        lblNumero.setName("lblUsuarioCadastro"); // NOI18N

        cbxNumero.setBackground(new java.awt.Color(3, 54, 73));
        cbxNumero.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        cbxNumero.setForeground(new java.awt.Color(232, 221, 203));
        cbxNumero.setText("S/N");
        cbxNumero.setFocusable(false);
        cbxNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxNumeroActionPerformed(evt);
            }
        });

        txtComplemento.setBackground(new java.awt.Color(232, 221, 203));
        txtComplemento.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtComplemento.setForeground(new java.awt.Color(0, 0, 0));
        txtComplemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComplementoActionPerformed(evt);
            }
        });

        lblComplemento.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblComplemento.setForeground(new java.awt.Color(232, 221, 203));
        lblComplemento.setLabelFor(txtEmail);
        lblComplemento.setText("Complemento:");
        lblComplemento.setName("lblUsuarioCadastro"); // NOI18N

        lblObrigatorio1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblObrigatorio1.setForeground(new java.awt.Color(255, 0, 0));
        lblObrigatorio1.setLabelFor(txtEmail);
        lblObrigatorio1.setText("*");
        lblObrigatorio1.setName("lblUsuarioCadastro"); // NOI18N

        lblObrigatorio2.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblObrigatorio2.setForeground(new java.awt.Color(255, 0, 0));
        lblObrigatorio2.setLabelFor(txtEmail);
        lblObrigatorio2.setText("*");
        lblObrigatorio2.setName("lblUsuarioCadastro"); // NOI18N

        lblObrigatorio3.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblObrigatorio3.setForeground(new java.awt.Color(255, 0, 0));
        lblObrigatorio3.setLabelFor(txtEmail);
        lblObrigatorio3.setText("*");
        lblObrigatorio3.setName("lblUsuarioCadastro"); // NOI18N

        lblObrigatorio.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblObrigatorio.setForeground(new java.awt.Color(255, 0, 0));
        lblObrigatorio.setLabelFor(txtEmail);
        lblObrigatorio.setText("*");
        lblObrigatorio.setName("lblUsuarioCadastro"); // NOI18N

        lblObrigatorio4.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblObrigatorio4.setForeground(new java.awt.Color(255, 0, 0));
        lblObrigatorio4.setLabelFor(txtEmail);
        lblObrigatorio4.setText("*");
        lblObrigatorio4.setName("lblUsuarioCadastro"); // NOI18N

        lblObrigatorio5.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblObrigatorio5.setForeground(new java.awt.Color(255, 0, 0));
        lblObrigatorio5.setLabelFor(txtEmail);
        lblObrigatorio5.setText("*");
        lblObrigatorio5.setName("lblUsuarioCadastro"); // NOI18N

        lblObrigatorio6.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblObrigatorio6.setForeground(new java.awt.Color(255, 0, 0));
        lblObrigatorio6.setLabelFor(txtEmail);
        lblObrigatorio6.setText("*");
        lblObrigatorio6.setName("lblUsuarioCadastro"); // NOI18N

        lblObrigatorio7.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblObrigatorio7.setForeground(new java.awt.Color(255, 0, 0));
        lblObrigatorio7.setLabelFor(txtEmail);
        lblObrigatorio7.setText("*");
        lblObrigatorio7.setName("lblUsuarioCadastro"); // NOI18N

        lblObrigatorio8.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblObrigatorio8.setForeground(new java.awt.Color(255, 0, 0));
        lblObrigatorio8.setLabelFor(txtEmail);
        lblObrigatorio8.setText("*");
        lblObrigatorio8.setName("lblUsuarioCadastro"); // NOI18N

        lblObrigatorio9.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblObrigatorio9.setForeground(new java.awt.Color(255, 0, 0));
        lblObrigatorio9.setLabelFor(txtEmail);
        lblObrigatorio9.setText("*");
        lblObrigatorio9.setName("lblUsuarioCadastro"); // NOI18N

        lblObrigatorio10.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblObrigatorio10.setForeground(new java.awt.Color(255, 0, 0));
        lblObrigatorio10.setLabelFor(txtEmail);
        lblObrigatorio10.setText("*");
        lblObrigatorio10.setName("lblUsuarioCadastro"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblSubtitulo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPossuoCadastro)
                        .addGap(27, 27, 27)
                        .addComponent(btnConfirmar)
                        .addGap(21, 21, 21))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitulo)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(lblTitulo2)
                                                    .addGap(0, 0, Short.MAX_VALUE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                    .addGap(0, 0, Short.MAX_VALUE)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(pswSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lblRequisitos1)
                                                        .addComponent(lblRequisitos2)
                                                        .addComponent(lblRequisitos3)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                            .addComponent(lblObrigatorio4)
                                                            .addGap(0, 0, 0)
                                                            .addComponent(lblSenha)))
                                                    .addGap(0, 0, Short.MAX_VALUE)))
                                            .addGap(18, 18, 18)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(pswConfirmarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(lblObrigatorio)
                                                    .addGap(0, 0, 0)
                                                    .addComponent(lblConfirmarSenha))))
                                        .addComponent(txtNome)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(lblObrigatorio2)
                                                    .addGap(1, 1, 1)
                                                    .addComponent(lblEmail)))
                                            .addGap(18, 18, 18)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(lblObrigatorio3)
                                                    .addGap(3, 3, 3)
                                                    .addComponent(lblCPF)))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblObrigatorio1)
                                        .addGap(0, 0, 0)
                                        .addComponent(lblNome)))
                                .addGap(31, 31, 31)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTitulo3)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(lblObrigatorio7)
                                                .addGap(0, 0, 0)
                                                .addComponent(lblBairro)))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(lblObrigatorio8)
                                                .addGap(0, 0, 0)
                                                .addComponent(lblCidade))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(lblObrigatorio5)
                                                .addGap(0, 0, 0)
                                                .addComponent(lblCPF1)))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(lblObrigatorio6)
                                                .addGap(0, 0, 0)
                                                .addComponent(lblEstado))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(lblObrigatorio9)
                                                .addGap(0, 0, 0)
                                                .addComponent(lblCidade1))
                                            .addComponent(txtLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(lblObrigatorio10)
                                                .addGap(0, 0, 0)
                                                .addComponent(lblNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txtNumero))
                                        .addGap(18, 18, 18)
                                        .addComponent(cbxNumero))
                                    .addComponent(lblComplemento)
                                    .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(27, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(0, 0, 0)
                .addComponent(lblSubtitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitulo3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(lblTitulo2)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(lblNome))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(lblObrigatorio1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, 0)
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblCPF)
                                    .addComponent(lblEmail)
                                    .addComponent(lblObrigatorio2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblObrigatorio3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtCPF)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblSenha)
                                    .addComponent(lblObrigatorio4))
                                .addGap(0, 0, 0)
                                .addComponent(lblRequisitos1)
                                .addGap(0, 0, 0)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblRequisitos2)
                                        .addGap(0, 0, 0)
                                        .addComponent(lblRequisitos3)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(pswConfirmarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addComponent(pswSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblConfirmarSenha)
                                        .addComponent(lblObrigatorio))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblCPF1)
                                    .addComponent(lblEstado)
                                    .addComponent(lblObrigatorio5)
                                    .addComponent(lblObrigatorio6))
                                .addGap(0, 0, 0)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblCidade)
                                            .addComponent(lblBairro)
                                            .addComponent(lblObrigatorio7)
                                            .addComponent(lblObrigatorio8))
                                        .addGap(0, 0, 0)
                                        .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(19, 19, 19)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cbxNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblCidade1)
                                            .addComponent(lblNumero)
                                            .addComponent(lblObrigatorio9)
                                            .addComponent(lblObrigatorio10))
                                        .addGap(0, 0, 0)
                                        .addComponent(txtLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblComplemento)
                                .addGap(0, 0, 0)
                                .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmar)
                    .addComponent(lblPossuoCadastro)
                    .addComponent(btnVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        
    }//GEN-LAST:event_txtEmailActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        
        txtNome.setText("");
        txtEmail.setText("");
        txtCPF.setText("");
        pswSenha.setText("");
        pswConfirmarSenha.setText("");
        txtCEP.setText("");
        cmbEstado.setSelectedItem("Escolha uma opção");
        txtBairro.setText("");
        txtCidade.setText("");
        txtLogradouro.setText("");
        txtNumero.setText("");  
        txtComplemento.setText("");
                
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed


    @SuppressWarnings("empty-statement")
    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
    
    boolean pagpreenchida = true;
        
    String nome = txtNome.getText();
    String email = txtEmail.getText();
    String CPF = txtCPF.getText();
    String senha = new String(pswSenha.getPassword());
    String csenha = new String(pswConfirmarSenha.getPassword());
    String cep = txtCEP.getText();
    String estado = (String) cmbEstado.getSelectedItem();
    String bairro = txtBairro.getText();
    String cidade = txtCidade.getText();
    String logradouro = txtLogradouro.getText();
    String numero = txtNumero.getText();
    String complemento = txtComplemento.getText();
    
    
    
    Scanner entrada = new Scanner(System.in);
    
    String nomeRegex = "^[A-Za-zÀ-ÿ]+ [A-Za-zÀ-ÿ]+( [A-Za-zÀ-ÿ]+)*$";
    String emailRegex = "^[a-zA-Z0-9._%+-]+@(gmail\\.com|outlook\\.com|yahoo\\.com)$";
    String cpfRegex = "^\\d{3}\\.?\\d{3}\\.?\\d{3}-?\\d{2}$";
    String senhaRegex = "^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[!@#$%&]).{8,}$";
    String cepRegex = "^\\d{5}-?\\d{3}$";

    
    while (pagpreenchida){
        
        if (nome.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "O campo Nome é obrigatório.", "Erro", JOptionPane.WARNING_MESSAGE);
            pagpreenchida = false;
            break;
        } else if (!nome.matches(nomeRegex)) {
            JOptionPane.showMessageDialog(rootPane, "O Nome deve conter pelo menos nome e sobrenome separados por espaço.", "Erro", JOptionPane.WARNING_MESSAGE);
            pagpreenchida = false;
            break;
        }

        if (email.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "O campo E-mail é obrigatório.", "Erro", JOptionPane.WARNING_MESSAGE);
            pagpreenchida = false;
            break;
        } else if (!email.matches(emailRegex)) {
            JOptionPane.showMessageDialog(rootPane, "O E-mail deve ser válido e pertencer aos domínios Gmail, Outlook ou Yahoo.", "Erro", JOptionPane.WARNING_MESSAGE);
            pagpreenchida = false;
            break;
        }

        if (CPF.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "O CPF deve ser válido (com ou sem pontuação).", "Erro", JOptionPane.WARNING_MESSAGE);
            pagpreenchida = false;
            break;
        } else if (!CPF.matches(cpfRegex)) {
            JOptionPane.showMessageDialog(rootPane, "O CPF deve conter apenas números.", "Erro", JOptionPane.WARNING_MESSAGE);
            pagpreenchida = false;
            break;
        }

        if (senha.isEmpty() || csenha.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Os campos Senha e Confirmar Senha são obrigatórios.", "Erro", JOptionPane.WARNING_MESSAGE);
            pagpreenchida = false;
            break;
        } else if (!senha.matches(senhaRegex)){
            JOptionPane.showMessageDialog(rootPane, "Esta senha não atende aos requisitos", "Erro", JOptionPane.WARNING_MESSAGE);
            pagpreenchida = false;
            break;
        }

        if (!senha.equals(csenha)) {
            JOptionPane.showMessageDialog(rootPane, "Os campos Senha e Confirmar Senha devem ser iguais.", "Erro", JOptionPane.WARNING_MESSAGE);
            pagpreenchida = false;
            break;
        }

        if (cep.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "O campo CEP é obrigatório.", "Erro", JOptionPane.WARNING_MESSAGE);
            pagpreenchida = false;
            break;
        } else if (!cep.matches(cepRegex)) {
            JOptionPane.showMessageDialog(rootPane, "O CEP deve conter 8 números, com ou sem hífen.", "Erro", JOptionPane.WARNING_MESSAGE);
            pagpreenchida = false;
            break;
        }

        if ("Escolha uma opção".equals(estado)) {
            JOptionPane.showMessageDialog(rootPane, "O campo Estado é obrigatório.", "Erro", JOptionPane.WARNING_MESSAGE);
            pagpreenchida = false;
            break;
        }

        if (bairro.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "O campo Bairro é obrigatório.", "Erro", JOptionPane.WARNING_MESSAGE);
            pagpreenchida = false;
            break;
        }

        if (cidade.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "O campo Cidade é obrigatório.", "Erro", JOptionPane.WARNING_MESSAGE);
            pagpreenchida = false;
            break;
        }

        if (logradouro.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "O campo Logradouro é obrigatório.", "Erro", JOptionPane.WARNING_MESSAGE);
            pagpreenchida = false;
            break;
        }
        
        if (numero.isEmpty() && !cbxNumero.isSelected()) {
            JOptionPane.showMessageDialog(rootPane, "Por favor insira um número ou desmarque a opção.", "Erro", JOptionPane.WARNING_MESSAGE);
            pagpreenchida = false;
            break;
        }
        else if (cbxNumero.isSelected()) {
            numero = "S/N";
        }
        break;
    }
    
    if (pagpreenchida == true){
        try {
            Cliente.inserirCliente(nome, email, CPF, senha, cep, estado, bairro, cidade, logradouro, numero, complemento);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao salvar", "Erro no salvamento", JOptionPane.ERROR_MESSAGE);
        }
        if (!Cliente.encontrado){
            dispose();
            Cliente.login_verificado = true;
        }
    }
        
        
    

    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void lblPossuoCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPossuoCadastroMouseClicked
        Cliente.login_verificado = false;
        formLogin login = new formLogin();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblPossuoCadastroMouseClicked

    private void lblPossuoCadastroMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPossuoCadastroMouseMoved
        int x = 0;
        int y = 51;
        int z = 255;
        
        lblPossuoCadastro.setForeground(new java.awt.Color(x, y, z));
    }//GEN-LAST:event_lblPossuoCadastroMouseMoved

    private void lblPossuoCadastroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPossuoCadastroMouseExited
        int x = 232;
        int y = 221;
        int z = 203;
        
        lblPossuoCadastro.setForeground(new java.awt.Color(x, y, z));
    }//GEN-LAST:event_lblPossuoCadastroMouseExited

    private void pswSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pswSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pswSenhaActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void pswConfirmarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pswConfirmarSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pswConfirmarSenhaActionPerformed

    private void txtCEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCEPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCEPActionPerformed

    private void txtBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBairroActionPerformed

    private void txtCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCidadeActionPerformed

    private void txtLogradouroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLogradouroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLogradouroActionPerformed

    private void txtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroActionPerformed

    private void cbxNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxNumeroActionPerformed
        if (cbxNumero.isSelected()) {
            txtNumero.setEditable(false);
            txtNumero.setText("");
        } else {
            txtNumero.setEditable(true);
        }    
    }//GEN-LAST:event_cbxNumeroActionPerformed

    private void txtComplementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComplementoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtComplementoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formCadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formCadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formCadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formCadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formCadastrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JCheckBox cbxNumero;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblCPF1;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblCidade1;
    private javax.swing.JLabel lblComplemento;
    private javax.swing.JLabel lblConfirmarSenha;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblObrigatorio;
    private javax.swing.JLabel lblObrigatorio1;
    private javax.swing.JLabel lblObrigatorio10;
    private javax.swing.JLabel lblObrigatorio2;
    private javax.swing.JLabel lblObrigatorio3;
    private javax.swing.JLabel lblObrigatorio4;
    private javax.swing.JLabel lblObrigatorio5;
    private javax.swing.JLabel lblObrigatorio6;
    private javax.swing.JLabel lblObrigatorio7;
    private javax.swing.JLabel lblObrigatorio8;
    private javax.swing.JLabel lblObrigatorio9;
    private javax.swing.JLabel lblPossuoCadastro;
    private javax.swing.JLabel lblRequisitos1;
    private javax.swing.JLabel lblRequisitos2;
    private javax.swing.JLabel lblRequisitos3;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblSubtitulo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTitulo2;
    private javax.swing.JLabel lblTitulo3;
    private javax.swing.JPasswordField pswConfirmarSenha;
    private javax.swing.JPasswordField pswSenha;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCEP;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtComplemento;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtLogradouro;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables
}
