package br.website.corex;

public class formSobre extends javax.swing.JFrame {

    /**
     * Creates new form sobrePanel
     */
    public formSobre() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nomeSite = new javax.swing.JLabel();
        desenvolvidoPor = new javax.swing.JLabel();
        integrante1 = new javax.swing.JLabel();
        integrante2 = new javax.swing.JLabel();
        integrante3 = new javax.swing.JLabel();
        integrante4 = new javax.swing.JLabel();
        integrante5 = new javax.swing.JLabel();
        buttonOK = new javax.swing.JButton();
        desenvolvidoPor1 = new javax.swing.JLabel();
        integrante6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CoreX - Sobre");

        jPanel1.setBackground(new java.awt.Color(3, 54, 73));

        nomeSite.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        nomeSite.setForeground(new java.awt.Color(232, 221, 203));
        nomeSite.setText("CoreX - Loja de Hardware");

        desenvolvidoPor.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        desenvolvidoPor.setForeground(new java.awt.Color(232, 221, 203));
        desenvolvidoPor.setText("Desenvolvido por:");

        integrante1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        integrante1.setForeground(new java.awt.Color(255, 255, 255));
        integrante1.setText("Bruno Andrade dos Santos");

        integrante2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        integrante2.setForeground(new java.awt.Color(255, 255, 255));
        integrante2.setText("Caio Fontes dos Santos Manhães");

        integrante3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        integrante3.setForeground(new java.awt.Color(255, 255, 255));
        integrante3.setText("Gabriel Alves Duarte");

        integrante4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        integrante4.setForeground(new java.awt.Color(255, 255, 255));
        integrante4.setText("Lucas de Santana dos Reis");

        integrante5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        integrante5.setForeground(new java.awt.Color(255, 255, 255));
        integrante5.setText("Yasmin Cibreiros Chagas da Silva");

        buttonOK.setBackground(new java.awt.Color(205, 179, 128));
        buttonOK.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        buttonOK.setForeground(new java.awt.Color(3, 54, 73));
        buttonOK.setText("Voltar");
        buttonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOKActionPerformed(evt);
            }
        });

        desenvolvidoPor1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        desenvolvidoPor1.setForeground(new java.awt.Color(232, 221, 203));
        desenvolvidoPor1.setText("Professor orientador:");

        integrante6.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        integrante6.setForeground(new java.awt.Color(255, 255, 255));
        integrante6.setText("Lázaro Pereira de Oliveira");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(nomeSite)
                .addContainerGap(134, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(integrante6)
                    .addComponent(integrante4)
                    .addComponent(integrante5)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(integrante3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(integrante2, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(integrante1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(desenvolvidoPor1)
                    .addComponent(desenvolvidoPor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonOK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(210, 210, 210))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nomeSite)
                .addGap(33, 33, 33)
                .addComponent(desenvolvidoPor, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(integrante1)
                .addGap(0, 0, 0)
                .addComponent(integrante2)
                .addGap(0, 0, 0)
                .addComponent(integrante3)
                .addGap(0, 0, 0)
                .addComponent(integrante4)
                .addGap(0, 0, 0)
                .addComponent(integrante5)
                .addGap(26, 26, 26)
                .addComponent(desenvolvidoPor1)
                .addGap(0, 0, 0)
                .addComponent(integrante6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(buttonOK, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOKActionPerformed
        dispose();
    }//GEN-LAST:event_buttonOKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formSobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formSobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formSobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formSobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formSobre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonOK;
    private javax.swing.JLabel desenvolvidoPor;
    private javax.swing.JLabel desenvolvidoPor1;
    private javax.swing.JLabel integrante1;
    private javax.swing.JLabel integrante2;
    private javax.swing.JLabel integrante3;
    private javax.swing.JLabel integrante4;
    private javax.swing.JLabel integrante5;
    private javax.swing.JLabel integrante6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nomeSite;
    // End of variables declaration//GEN-END:variables
}
